# model.pyi
from typing import Any, List, Optional, Type
from sqlalchemy import Engine
from sqlmodel_toolkit.query import Query, ModelT

class Model:
    _engine: Engine | None

    @classmethod
    def set_engine(cls, engine: Engine) -> None: ...
    @classmethod
    def get_engine(cls) -> Engine: ...
    @classmethod
    def query(cls: Type[ModelT]) -> Query[ModelT]: ...
    @classmethod
    def create(cls: Type[ModelT], **kwargs: Any) -> ModelT: ...
    def save(self: ModelT) -> ModelT: ...
    def delete(self) -> None: ...
    def update(self: ModelT, **kwargs: Any) -> ModelT: ...
    def reload(self: ModelT) -> ModelT: ...

    # Query delegation
    @classmethod
    def find(cls: Type[ModelT], value: Any) -> Optional[ModelT]: ...
    @classmethod
    def find_by(cls: Type[ModelT], **kwargs: Any) -> Optional[ModelT]: ...
    @classmethod
    def where(cls: Type[ModelT], *conditions: Any, **kwargs: Any) -> Query[ModelT]: ...
    @classmethod
    def not_(cls: Type[ModelT], *conditions: Any, **kwargs: Any) -> Query[ModelT]: ...
    @classmethod
    def with_(cls: Type[ModelT], *relationships: str) -> Query[ModelT]: ...
    @classmethod
    def order_by(cls: Type[ModelT], *args: Any, **kwargs: Any) -> Query[ModelT]: ...
    @classmethod
    def limit(cls: Type[ModelT], count: int) -> Query[ModelT]: ...
    @classmethod
    def offset(cls: Type[ModelT], count: int) -> Query[ModelT]: ...
    @classmethod
    def distinct(cls: Type[ModelT]) -> Query[ModelT]: ...
    @classmethod
    def all(cls: Type[ModelT]) -> list[ModelT]: ...
    @classmethod
    def first(cls: Type[ModelT]) -> Optional[ModelT]: ...
    @classmethod
    def one(cls: Type[ModelT]) -> ModelT: ...
    @classmethod
    def count(cls) -> int: ...
